# Generated by Django 4.0.6 on 2022-09-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_product_pro_slug_33a021_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbookmark',
            options={'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
    ]
