TITLE_MAX_LEN = 50
DESCRIPTION_MAX_LEN = 1000
NOTE_MAX_LEN = 1000
CATEGORY_MAX_LEN = 20
SLUG_MAX_LEN = TITLE_MAX_LEN + 12

MIN_PRICE = 10
MAX_PRICE = 5_000

MAX_EDIT_ALLOWED = 1
IMAGE_FOLDER = "products"
ALLOWED_IMAGE_EXTENSIONS = ["jpg", "jpeg", "png", "gif"]
MAX_FILE_SIZE = 4 * 1024 * 1024

ERROR_MESSAGES = {
    'FILE_SIZE_EXCEEDS': 'Please upload image less than 1MB',
}
